### ISSUE TITLE
Loops, typos

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#104]
file: exercises/loops/assignment-remove-backspaces.en.md
text: While any mapping between symbols and numbers will do, **but** it's always nice if people **agreed** on one specific mapping.
correct: While any mapping between symbols and numbers will do, it's always nice if people agree on one specific mapping.

file: exercises/loops/assignment-remove-backspaces.en.md
text:
```
>>> remove_backspaces("abc\b\bxyz")
"axyz"
```
explanation: "axyz" should be "abxyz"

file: exercises/loops/explanation-for.en.md
text:
```
i = 0
while i < i_max:
    # ...
    i += 1
```
explanation: `i_max `is not defined. Same for the next code snippet in the same file. Not a typo, correct it if you consider it necessary.

**Comment by brechtnelye** [comment]
>>> remove_backspaces("abc\b\bxyz")
"axyz"

There are( 2): \b\b backspaces -> removing bc and resulting in 'axyz'

The second part of your issue is just an example of a common pattern. 
Since you add a condition to your i = 0 which often come in the form of a parameter. 
It's supposed to illustrate that python made it easier by not having to define them with the iteration:
for i in range(start, stop, step)

I'm sure they will change if it's necessary.
