### ISSUE TITLE
Functions returning nothing -- duplicate

### ISSUE THREAD

**Issue by karenbaerts** [ucll-programming/course-material#78]
Theory under 'None - Introduction - Functions returning none' is also covered under 'None - Return Value'.

**Comment by brechtnelye** [comment]
I've been looking over it and indeed there is duplication. My personal experience with students is they don't read all the way down to the bottom in most cases, since the importance of knowing functions do return something (none) 
The repetition is not a bad thing. 

It's a consideration the lectors-team will have to decide on. For now I'm not changing it until said decision is made. 
Feel free to comment on it, if you like it to be integrated or removed.
